export const products = [
  {
    brand: "Minimal Desk",
    name: "슬림 모듈 데스크 1200",
    discount: 35,
    price: "129,000원",
    rating: 4.8,
    reviews: 1203,
    img: "./img/product/desk1.jpg",
  },
  {
    brand: "Ergo Line",
    name: "인체공학 메쉬 체어",
    discount: 28,
    price: "159,000원",
    rating: 4.7,
    reviews: 842,
    img: "./img/product/chair1.jpg",
  },
  {
    brand: "Storage Lab",
    name: "3단 서랍 수납장 400",
    discount: 30,
    price: "79,000원",
    rating: 4.9,
    reviews: 2031,
    img: "./img/product/storage1.jpg",
  },
  {
    brand: "Minimal Desk",
    name: "L자형 코너 데스크 1400",
    discount: 32,
    price: "219,000원",
    rating: 4.6,
    reviews: 517,
    img: "./img/product/desk2.jpg",
  },
  {
    brand: "Executive",
    name: "프리미엄 가죽 체어",
    discount: 25,
    price: "249,000원",
    rating: 4.9,
    reviews: 302,
    img: "./img/product/chair2.jpg",
  },
  {
    brand: "Storage Lab",
    name: "벽면 시스템 선반 세트",
    discount: 40,
    price: "189,000원",
    rating: 4.8,
    reviews: 921,
    img: "./img/product/storage2.jpg",
  },
];
